### ISSUE TITLE
Installation issue?

### ISSUE THREAD

**Issue by 017Bluefield** [Dischan/dismae-ui#2]
I don't want to pile too much onto development at a time, but I figured that this could be useful somehow.

Basically, I can't install Dismae UI. It says that there was an issue in the installation process.

Below is the SquirrelSetup file (in .txt form) that the error gave me, as well as a DxDiag file for the system I tried installing D. UI on.
- [SquirrelSetup.txt](https://github.com/Dischan/dismae-ui/files/428158/SquirrelSetup.txt)
- [DxDiag.txt](https://github.com/Dischan/dismae-ui/files/428159/DxDiag.txt)

**Comment by VolatileCarbon** [comment]
Right now Dismae only supports 64-bit windows installations which is why you got the error (your windows installation is 32-bit). Might support 32 bit later though.
